USE TourAppDb;
GO

INSERT INTO Tours
VALUES (DEFAULT, DEFAULT, 'Active', 'The Sea Explorer', 'Spain', 'Explore Spain', 'Easy', 10, 4, DATEADD(day, 4, GETUTCDATE()), 372, NULL, 4, 7, NEWID(), 'spainTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Forest Hiker', 'France', 'Explore France', 'Medium', 8, 5, DATEADD(day, 3, GETUTCDATE()), 534, NULL, 5, 8, NEWID(), 'franceTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Mountain Conquer', 'Russia', 'Explore Russia', 'Hard', 4, 4, DATEADD(day, 4, GETUTCDATE()), 853, NULL, 4, 10, NEWID(), 'russiaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The River Drifter', 'Brazil', 'Explore Amazonka River', 'Hard', 8, 3.5, DATEADD(day, 8, GETUTCDATE()), 654, NULL, 4, 8, NEWID(), 'brazilTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Arctic Roamer', 'Dania', 'Explore Greenland', 'Hard', 9, 4, DATEADD(day, 10, GETUTCDATE()), 432, NULL, 7, 10, NEWID(), 'greenlandTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Desert Wanderer', 'Morocco', 'Explore Sahara Dunes', 'Medium', 6, 4.5, DATEADD(day, 5, GETUTCDATE()), 489, NULL, 3, 6, NEWID(), 'moroccoTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Glacier Trekker', 'Iceland', 'Explore Icelandic Glaciers', 'Hard', 5, 5, DATEADD(day, 6, GETUTCDATE()), 721, NULL, 6, 9, NEWID(), 'icelandTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Jungle Pathfinder', 'Peru', 'Explore Amazon Jungle', 'Medium', 7, 4.2, DATEADD(day, 7, GETUTCDATE()), 578, NULL, 5, 7, NEWID(), 'peruTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Canyon Voyager', 'USA', 'Explore Grand Canyon', 'Easy', 9, 3.8, DATEADD(day, 4, GETUTCDATE()), 395, NULL, 4, 6, NEWID(), 'usaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Volcano Seeker', 'Indonesia', 'Explore Mount Bromo', 'Hard', 6, 4.7, DATEADD(day, 9, GETUTCDATE()), 612, NULL, 6, 8, NEWID(), 'indonesiaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Highland Rambler', 'Scotland', 'Explore Scottish Highlands', 'Medium', 7, 4.3, DATEADD(day, 5, GETUTCDATE()), 498, NULL, 5, 7, NEWID(), 'scotlandTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The City Wanderer', 'Japan', 'Explore Tokyo Streets', 'Easy', 6, 4.1, DATEADD(day, 3, GETUTCDATE()), 412, NULL, 3, 5, NEWID(), 'japanTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Outback Adventurer', 'Australia', 'Explore Australian Outback', 'Hard', 8, 4.6, DATEADD(day, 7, GETUTCDATE()), 689, NULL, 6, 9, NEWID(), 'australiaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Nordic Voyager', 'Norway', 'Explore Norwegian Fjords', 'Medium', 5, 4.4, DATEADD(day, 6, GETUTCDATE()), 523, NULL, 5, 8, NEWID(), 'norwayTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Safari Tracker', 'Kenya', 'Explore Maasai Mara', 'Hard', 7, 4.8, DATEADD(day, 8, GETUTCDATE()), 745, NULL, 6, 10, NEWID(), 'kenyaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Temple Explorer', 'India', 'Explore Ancient Temples', 'Medium', 6, 4.2, DATEADD(day, 5, GETUTCDATE()), 467, NULL, 4, 7, NEWID(), 'indiaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Island Hopper', 'Philippines', 'Explore Palawan Islands', 'Easy', 5, 3.9, DATEADD(day, 4, GETUTCDATE()), 388, NULL, 3, 6, NEWID(), 'philippinesTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Andes Ascender', 'Chile', 'Explore Andes Mountains', 'Hard', 9, 4.9, DATEADD(day, 9, GETUTCDATE()), 812, NULL, 7, 10, NEWID(), 'chileTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Steppe Rider', 'Mongolia', 'Explore Mongolian Steppe', 'Medium', 7, 4.0, DATEADD(day, 6, GETUTCDATE()), 501, NULL, 5, 8, NEWID(), 'mongoliaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Coastline Cruiser', 'Portugal', 'Explore Algarve Coast', 'Easy', 6, 3.7, DATEADD(day, 3, GETUTCDATE()), 376, NULL, 3, 5, NEWID(), 'portugalTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Rainforest Roamer', 'Costa Rica', 'Explore Costa Rican Rainforest', 'Medium', 8, 4.5, DATEADD(day, 7, GETUTCDATE()), 589, NULL, 5, 9, NEWID(), 'costaRicaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Alpine Trekker', 'Switzerland', 'Explore Swiss Alps', 'Hard', 6, 4.6, DATEADD(day, 6, GETUTCDATE()), 678, NULL, 6, 9, NEWID(), 'switzerlandTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Cultural Curator', 'Italy', 'Explore Italian Heritage', 'Easy', 5, 4.0, DATEADD(day, 4, GETUTCDATE()), 432, NULL, 4, 6, NEWID(), 'italyTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Baltic Explorer', 'Estonia', 'Explore Baltic Coast', 'Medium', 7, 4.3, DATEADD(day, 5, GETUTCDATE()), 495, NULL, 5, 7, NEWID(), 'estoniaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Sahara Nomad', 'Algeria', 'Explore Sahara Oasis', 'Hard', 8, 4.7, DATEADD(day, 8, GETUTCDATE()), 722, NULL, 6, 9, NEWID(), 'algeriaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Balkan Trailblazer', 'Croatia', 'Explore Dalmatian Coast', 'Medium', 6, 4.2, DATEADD(day, 5, GETUTCDATE()), 478, NULL, 4, 7, NEWID(), 'croatiaTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Andes Explorer', 'Ecuador', 'Explore Cotopaxi Volcano', 'Hard', 7, 4.5, DATEADD(day, 7, GETUTCDATE()), 603, NULL, 5, 8, NEWID(), 'ecuadorTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Fjord Wanderer', 'Sweden', 'Explore Swedish Fjords', 'Medium', 6, 4.1, DATEADD(day, 6, GETUTCDATE()), 456, NULL, 4, 7, NEWID(), 'swedenTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Island Adventurer', 'New Zealand', 'Explore South Island', 'Hard', 9, 4.9, DATEADD(day, 9, GETUTCDATE()), 799, NULL, 7, 10, NEWID(), 'newZealandTour.png'),
       (DEFAULT, DEFAULT, 'Active', 'The Steppe Voyager', 'Kazakhstan', 'Explore Kazakh Plains', 'Medium', 7, 4.2, DATEADD(day, 6, GETUTCDATE()), 512, NULL, 5, 8, NEWID(), 'kazakhstanTour.png');